
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY config ./config
COPY controllers/userController.js ./controllers/
COPY middleware ./middleware
COPY routes/userRoutes.js ./routes/
COPY userServer.js .

ENV NODE_ENV=production
EXPOSE 3000
CMD ["node", "userServer.js"]
