
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY config ./config
COPY controllers/blogController.js ./controllers/
COPY middleware ./middleware
COPY routes/blogRoutes.js ./routes/
COPY blogServer.js .

ENV NODE_ENV=production
EXPOSE 3001
CMD ["node", "blogServer.js"]